info:
  name: Create Application
  type: http
  seq: 1

http:
  method: POST
  url: http://localhost:8080/api/applications
  body:
    type: json
    data: |-
      {
        "name": "CloudDeploy Docker Test",
        "repositoryUrl": "https://github.com/griz2/cloud-deploy",
        "dockerfilePath": "backend/Dockerfile",
        "environment": "DEVELOPMENT",
        "healthCheckUrl": "/actuator/health"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
