info:
  name: Create Application
  type: http
  seq: 1

http:
  method: POST
  url: http://localhost:8080/api/applications
  body:
    type: json
    data: |-
      {
        "name": "CloudDeploy",
        "repositoryUrl": "https://github.com/michael/clouddeploy",
        "environment": "DEVELOPMENT",
        "healthCheckUrl": "http://localhost:8080/actuator/health"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
