spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/clouddeploy
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info