spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/clouddeploy
    username: postgres
    password: DoctorWho10!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info